// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvdrcucnutebfefdqnhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2ZHJjdWNudXRlYmZlZmRxbmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTIzNjIsImV4cCI6MjA1ODU2ODM2Mn0._wTyG3brSd6sVixzglNCcGPoHYPOem_Qxj5DFrevKRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);